In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
rev_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", rev_arr)

Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
f_arr = arr.flatten()
print("Original array:", arr)
print("Flattened array:", f_arr)

Original array: [1 2 3 4 5]
Flattened array: [1 2 3 4 5]


In [ ]:
import numpy as np
array2 = np.array([[1,2,3],[2,4,5],[1,2,3]])
r_arr = arr.ravel()
print("Original array:",arr)
print("Flattened array:",r_arr)

Original array: [1 2 3 4 5]
Flattened array: [1 2 3 4 5]


In [1]:
import numpy as np
array1=np.array([[1,2],[3,4]])
array2=np.array([[1,2],[3,4]])
compare = array1 == array2

print("compare the array \n",compare)

compare the array 
 [[ True  True]
 [ True  True]]


In [2]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print(f"Most frequent value: {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")

Most frequent value: 1
Indices of the most frequent value: [0 5 7 8 9]


In [2]:
import numpy as np
x = np.array([1, 1 , 1 , 2 , 3 , 4 , 2 , 4 , 3 , 3])
values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print(f"Most frequent value: {most_frequent_value}")
print(f"Indices of the most frequent value: {indices}")

Most frequent value: 1
Indices of the most frequent value: [0 1 2]


In [4]:
import numpy as np
gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
sum_is = np.sum(gfg)
print("Sum of array : ",sum_is)

Sum of array :  45


In [3]:
import numpy as np
gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
sum_is = np.sum(gfg,axis=1)
print("Sum of array row wise : ",sum_is)

Sum of array row wise :  [14 16 15]


In [5]:
import numpy as np
gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
sum_is = np.sum(gfg,axis=0)
print("Sum of array column wise : ",sum_is)

Sum of array column wise :  [20  9 16]


In [ ]:
import numpy as np
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
result = np.dot(p, q)
print("Matrix multiplication result:\n", result)
cov = np.cov(p, q)
print("Covariance matrix:\n",cov)

Matrix multiplication result:
 [[16 19]
 [26 31]]
Covariance matrix:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
import numpy as np
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
result = np.dot(p, q)
print("Matrix multiplication result:\n",result)

Matrix multiplication result:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
sum_diagonal = np.trace(n_array)
eigenvalues = np.linalg.eigvals(n_array)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print("Sum of diagonal elements:", sum_diagonal)
print("Eigenvalues of matrix:", eigenvalues)
print("Eigenvectors of matrix:\n", eigenvectors)
print("Inverse of matrix:\n", inverse_matrix)
print("Determinant of matrix:", determinant)

Sum of diagonal elements: 176
Eigenvalues of matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001


In [ ]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
outer = np.outer(x, y)
print("Inner product:\n", inner)
print("Outer product:\n", outer)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor = np.floor(a)
ceiling = np.ceil(a)
truncated = np
rounded = np.round(a)
print("Floor values:", floor)
print("Ceiling values:", ceiling)
print("Rounded values:", rounded)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3],[-4, 5, -6]])

abs_values = np.abs(array)
print("Element-wise absolute values:\n", abs_values)

array = np.array([[1, -2, 3],[-4, 5, -6]])
percentile_25 = np.percentile(array, 25)
print("25th percentile of flattened array:\n", percentile_25)

percentile_50 = np.percentile(array, 50)
print("50th percentile of flattened array:\n", percentile_50)

percentile_75 = np.percentile(array, 75)
print("75th percentile of flattened array:\n", percentile_75)

mean = np.mean(array)
print("Mean of flattened array:", mean)

median = np.median(array)
print("Median of flattened array:", median)

std_dev = np.std(array)
print("Standard deviation of flattened array:", std_dev)


Element-wise absolute values:
 [[1 2 3]
 [4 5 6]]
25th percentile of flattened array:
 -3.5
50th percentile of flattened array:
 -0.5
75th percentile of flattened array:
 2.5
Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard deviation of flattened array: 3.8622100754188224


In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)

sorted_indices = np.argsort(array)

four_smallest_elements = np.partition(array, 4)[:4]

five_largest_elements = np.partition(array, -5)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", four_smallest_elements)
print("5 largest elements:", five_largest_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [16 10 16 52]
5 largest elements: [ 16  52  62  54 453]


In [ ]:
import numpy as np

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == np.floor(array)]

float_elements = array[array != np.floor(array)]

print("Integer elements only:", integer_elements)
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [6]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)

    if img.mode == 'RGB':
        np.savetxt('rgb_image_array.txt', img_array.reshape(-1, 3), fmt='%d', delimiter=',')

    elif img.mode == 'L':
        np.savetxt('grayscale_image_array.txt', img_array, fmt='%d', delimiter=',')

    else:
        raise ValueError("Unsupported image mode: {}".format(img.mode))

img_to_array('djokovic.png')

In [12]:
import numpy as np 
data = np.genfromtxt("rgb_image_array.txt", dtype=int, encoding=None, delimiter=",") 
print(data) 


[[ 96 132 158]
 [ 96 132 158]
 [ 96 132 156]
 ...
 [108 139 157]
 [108 140 155]
 [108 140 155]]
